--
-- Tabellenstruktur für Tabelle `ACTPOS`
--

CREATE TABLE IF NOT EXISTS `ACTPOS` (
  `ACTP_ID` INTEGER(20) PRIMARY KEY ASC,
  `ACTP_TEIL_ID` INTEGER(20) NOT NULL,
  `ZEITPUNKT` TEXT(20) NOT NULL,
  `LATITUDE` REAL NOT NULL,
  `LONGITUDE` REAL NOT NULL,
  `GPS_PUNKT` INTEGER(20),
  `WIND` INTEGER(11),
  `GANG` INTEGER(11),
  `ENERGIE` INTEGER(11),
  `PULS` INTEGER(11),
  `RPM` REAL,
  `LEISTUNG` REAL,
  `GESCHWINDIGKEIT` REAL,
  `STRECKE` REAL,
  `STEIGUNG` REAL,
  `HOEHE` REAL,
  `ZPSTRECKE` REAL,
  FOREIGN KEY(`ACTP_TEIL_ID`) REFERENCES TEILNAHME(`TEIL_ID`)
);

CREATE INDEX `ACTP_GPS_PUNKT_I` ON `ACTPOS` (`GPS_PUNKT` ASC);
CREATE INDEX `ACTP_TEIL_ID_I` ON `ACTPOS` (`ACTP_TEIL_ID` ASC);



