--
-- Tabellenstruktur für Tabelle `ERGEBNIS`
--

CREATE TABLE IF NOT EXISTS `ERGEBNIS` (
  `ERGE_ID` INTEGER(20) PRIMARY KEY ASC,
  `ERGE_TEIL_ID` INTEGER(20) NOT NULL,
  `ERGE_RENN_ID` INTEGER(20) NOT NULL,
  `PLATZ` INTEGER(11) NOT NULL,
  `ZEIT` TEXT(10),
  `ENERGIE` INTEGER(11),
  `RPM_SCHNITT` REAL,
  `PULS_SCHNITT` REAL,
  `LEISTUNG_SCHNITT` REAL,
  `ZPSTRECKE` REAL,
  FOREIGN KEY(`ERGE_TEIL_ID`) REFERENCES TEILNAHME(`TEIL_ID`),
  FOREIGN KEY(`ERGE_RENN_ID`) REFERENCES RENNEN(`RENN_ID`)
--  KEY `ERGE_TEIL_ID_I` (`ERGE_TEIL_ID`),
--  KEY `ZEIT_I` (`ZEIT`),
--  KEY `ERGE_RENN_ID_I` (`ERGE_RENN_ID`)
);
CREATE UNIQUE INDEX `ERGEBNIS_UK` ON `ERGEBNIS` (`ERGE_TEIL_ID` ASC, `ERGE_RENN_ID` ASC);
CREATE INDEX `ERGEBNIS_ZEIT_I` ON `ERGEBNIS` (`ZEIT` ASC);

