--
-- Tabellenstruktur für Tabelle `RENNEN`
--

CREATE TABLE IF NOT EXISTS `RENNEN` (
  `RENN_ID` INTEGER(20) PRIMARY KEY ASC,
  `BEZEICHNUNG` TEXT(50) NOT NULL,
  `STARTZEIT` TEXT(20) NOT NULL,
  `TEILNEHMER` INTEGER(11) DEFAULT 0,
  `TYP` TEXT(50),
  `MINLEISTUNG` INTEGER(11),
  `MAXLEISTUNG` INTEGER(11),
  `DYNAMIK` INTEGER(11) DEFAULT 0,
  `TOUR` TEXT(64) NOT NULL,
  `STATUS` INTEGER(11) DEFAULT 0,
  `LETZT_GPS` INTEGER(11),
  `TEILNEHMERLIMIT` INTEGER(11),
  `PULSMIN` INTEGER(11),
  `PULSMAX` INTEGER(11),
  `SCHIKANE` INTEGER(11) DEFAULT 0,
  `LEISTUNGSFAKTOR` REAL DEFAULT 1.0,
  `TFNORMAL` INTEGER(11),
  `TFMIN` INTEGER(11),
  `TFMAX` INTEGER(11)
);
CREATE INDEX `BEZEICHNUNG_I` ON `RENNEN` (`BEZEICHNUNG` ASC);
CREATE INDEX `STARTZEIT_I` ON `RENNEN` (`STARTZEIT` ASC);
CREATE INDEX `STATUS_I` ON `RENNEN` (`STATUS` ASC);

