--
-- Tabellenstruktur für Tabelle `TEILNAHME`
--

CREATE TABLE IF NOT EXISTS `TEILNAHME` (
  `TEIL_ID` INTEGER(20) PRIMARY KEY ASC,
  `TEIL_USER_ID` INTEGER(20) NOT NULL,
  `TEIL_RENN_ID` INTEGER(20) NOT NULL,
  `ANGEMELDET_AM` TEXT(10),
  `PLATZ` INTEGER(11),
  `ZEIT` TEXT(16),
  FOREIGN KEY(`TEIL_USER_ID`) REFERENCES USER(`USER_ID`),
  FOREIGN KEY(`TEIL_RENN_ID`) REFERENCES RENNEN(`RENN_ID`)
);

CREATE UNIQUE INDEX `TEILNAHME_UK` ON `TEILNAHME` (`TEIL_USER_ID` ASC, `TEIL_RENN_ID` ASC);

