--
-- Tabellenstruktur für Tabelle `USER`
--
/* MySQL:
CREATE TABLE IF NOT EXISTS `USER` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SNR` char(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `NAME` char(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `VORNAME` char(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ORT` char(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ABLAUF_AM` date DEFAULT NULL,
  `GEBURTSJAHR` int(11) DEFAULT NULL,
  `FGEWICHT` int(11) DEFAULT NULL,
  `MAXLEISTUNG` int(11) DEFAULT NULL,
  `MINLEISTUNG` int(11) DEFAULT NULL,
  `BGEWICHT` int(11) DEFAULT NULL,
  `TRAINER` char(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `IND_SNR` (`SNR`),
  UNIQUE KEY `Ind_Name_Vorname` (`NAME`,`VORNAME`),
  KEY `Ind_Name` (`NAME`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=36 ;
*/ 
-- SQLite:
CREATE TABLE IF NOT EXISTS `USER` (
  `USER_ID` INTEGER(20) PRIMARY KEY ASC,
  `SNR` TEXT(20),
  `NAME` TEXT(50),
  `VORNAME` TEXT(50),
  `ORT` TEXT(50),
  `ABLAUF_AM` TEXT(10),
  `GEBURTSJAHR` INTEGER(11),
  `FGEWICHT` INTEGER(11),
  `MAXLEISTUNG` INTEGER(11),
  `MINLEISTUNG` INTEGER(11),
  `BGEWICHT` INTEGER(11),
  `TRAINER` TEXT(50)
) 

